### ISSUE TITLE
Bad line checker

### ISSUE THREAD

**Issue by dsonyy** [dsonyy/hyper-tic-tac-toe#1]
![image](https://user-images.githubusercontent.com/25373558/52494335-fcbc4e00-2bcd-11e9-9293-30620bd5907c.png)

**Comment by dsonyy** [comment]
![image](https://user-images.githubusercontent.com/25373558/52753098-b44dc780-2ff5-11e9-841c-3b8df52c4d14.png)

**Comment by KrzysztofZawisla** [comment]
ok
